### ISSUE TITLE
npm install failure

### ISSUE THREAD

**Issue by kargakis** [BarnBridge/barnbridge-frontend#146]
Unclear why this occurs with a fresh npm install. Tried both with node 14 and 12, getting the same issue.
```
npm ERR! Could not install from "node_modules/web3-provider-engine/node_modules/eth-sig-util/ethereumjs-abi@git+https:/github.com/ethereumjs/ethereumjs-abi.git" as it does not contain a package.json file.
```

**Comment by wfm-slava** [comment]
@kargakis just try to remove package-lock.json file under root folder and re-execute "npm install" command

**Comment by kargakis** [comment]
Thanks @wfm-slava for the suggestion, it worked!
